package client.gui;

import client.gui.util.frameUtil;
import client.service.dao.cardDao;
import client.service.impl.cardImpl;

import javax.swing.*;
import java.util.regex.Pattern;

/**
 *
 * @author tinysean
 */
public class addCardFrame extends javax.swing.JFrame {

    /**
     * Creates new form addCardFrame
     */
    private String userName;
    public addCardFrame(String userName) {
        this.userName = userName;
        initComponents();
        frameUtil.setCenter(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        cardNumber = new javax.swing.JLabel();
        cardPassword = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        cardNumberText = new javax.swing.JTextField();
        balanceText = new javax.swing.JTextField();
        cardPasswordText = new javax.swing.JPasswordField();
        addButton = new javax.swing.JButton();
        retuanButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("添加卡");

        cardNumber.setText("卡号");

        cardPassword.setText("密码");

        balance.setText("余额");

        addButton.setText("添加");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        retuanButton.setText("返回");
        retuanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retuanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cardPassword)
                                                        .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cardNumber))
                                                .addGap(46, 46, 46)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(cardNumberText, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                                        .addComponent(cardPasswordText)
                                                        .addComponent(balanceText)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(91, 91, 91)
                                                .addComponent(addButton)
                                                .addGap(51, 51, 51)
                                                .addComponent(retuanButton)))
                                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cardNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cardNumber))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cardPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cardPassword))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(balanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(balance))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addButton)
                                        .addComponent(retuanButton))
                                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>
    private void empty(){
        cardNumberText.setText("");
        cardPasswordText.setText("");
        balanceText.setText("");
    }

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String userName = cardNumberText.getText();
        String passWord = String.valueOf(cardPasswordText.getPassword());
        if(!Pattern.matches("\\w{1,18}", userName)){
            JOptionPane.showMessageDialog(this, "卡号长度必须在1～18","失败",JOptionPane.ERROR_MESSAGE);
            empty();
        }else if(!Pattern.matches("\\w{1,8}", passWord)){
            JOptionPane.showMessageDialog(this, "密码长度必须在1～8","失败",JOptionPane.ERROR_MESSAGE);
            empty();
        }else if(!Pattern.matches("^(([0-9]+\\\\.[0-9]*[1-9][0-9]*)|([0-9]*[1-9][0-9]*\\\\.[0-9]+)|([0-9]*[1-9][0-9]*))$",balanceText.getText())){
            JOptionPane.showMessageDialog(this, "充值金额必须为正","失败",JOptionPane.ERROR_MESSAGE);
            empty();
        }else{
            double balance = Double.parseDouble(balanceText.getText());
            cardDao carddao = new cardImpl();
            int result = carddao.addCard(userName, passWord, balance);
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "卡添加成功", "成功", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "卡添加失败", "失败", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void retuanButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        MainJFrame jFrame = new MainJFrame(this.userName);
        jFrame.setVisible(true);
        this.dispose();
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCardFrame("no-root").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton addButton;
    private javax.swing.JLabel balance;
    private javax.swing.JTextField balanceText;
    private javax.swing.JLabel cardNumber;
    private javax.swing.JTextField cardNumberText;
    private javax.swing.JLabel cardPassword;
    private javax.swing.JPasswordField cardPasswordText;
    private javax.swing.JButton retuanButton;
    // End of variables declaration
}

